-- The game's string tables, rebuilt from the current language.
--
-- These used to be literals inside init(). They live here instead because they
-- have to be rebuilt when the language changes, and because a thousand lines of
-- hero and item copy was the bulk of what init() was.
--
-- Only the tables holding text are here. Colours, tiers, stat multipliers and
-- the rest of the data stay in main.lua: none of it changes with the language.

-- How far a class is from its next tier, drawn as "3/6" with whichever number
-- is currently in force picked out in yellow. The level colouring is the same
-- in every language, so it is built here and handed to T() as an argument
-- rather than being spelled out inside every translated string.
local function ylb1(lvl) return lvl == 1 and 'yellow' or 'light_bg' end
local function ylb2(lvl) return lvl == 2 and 'yellow' or 'light_bg' end
local function ylb3(lvl) return lvl == 3 and 'yellow' or 'light_bg' end

local function cls2(lvl, a, b)
  return '[' .. ylb1(lvl) .. ']' .. a .. '[light_bg]/[' .. ylb2(lvl) .. ']' .. b
end

local function cls3(lvl, a, b, c)
  return '[' .. ylb1(lvl) .. ']' .. a .. '[light_bg]/[' .. ylb2(lvl) .. ']' .. b .. '[light_bg]/[' .. ylb3(lvl) .. ']' .. c
end

-- The same shape for item levels, where all three tiers are always shown.
local function ts(lvl, a, b, c)
  return cls3(lvl, tostring(a), tostring(b), tostring(c)) .. '[fg]'
end


-- Which colour each hero's level 3 effect is titled in. Not translatable, and
-- kept apart from the name so that the greyed-out version of the same title
-- does not need a second copy of the text.
local effect_colors = {
  ['vagrant'] = 'fg',
  ['swordsman'] = 'yellow',
  ['wizard'] = 'blue',
  ['magician'] = 'blue',
  ['archer'] = 'green',
  ['scout'] = 'red',
  ['cleric'] = 'green',
  ['outlaw'] = 'red',
  ['blade'] = 'yellow',
  ['elementor'] = 'blue',
  ['saboteur'] = 'orange',
  ['bomber'] = 'orange',
  ['stormweaver'] = 'blue',
  ['sage'] = 'purple',
  ['squire'] = 'yellow',
  ['cannoneer'] = 'orange',
  ['dual_gunner'] = 'green',
  ['hunter'] = 'green',
  ['sentry'] = 'green',
  ['chronomancer'] = 'blue',
  ['spellblade'] = 'blue',
  ['psykeeper'] = 'fg',
  ['engineer'] = 'orange',
  ['plague_doctor'] = 'purple',
  ['barbarian'] = 'yellow',
  ['juggernaut'] = 'yellow',
  ['lich'] = 'blue',
  ['cryomancer'] = 'blue',
  ['pyromancer'] = 'red',
  ['corruptor'] = 'orange',
  ['beastmaster'] = 'red',
  ['launcher'] = 'orange',
  ['jester'] = 'red',
  ['assassin'] = 'purple',
  ['host'] = 'orange',
  ['carver'] = 'green',
  ['bane'] = 'purple',
  ['psykino'] = 'fg',
  ['barrager'] = 'green',
  ['highlander'] = 'yellow',
  ['fairy'] = 'green',
  ['priest'] = 'green',
  ['infestor'] = 'orange',
  ['flagellant'] = 'red',
  ['arcanist'] = 'blue2',
  ['illusionist'] = 'blue2',
  ['artificer'] = 'blue2',
  ['witch'] = 'purple',
  ['silencer'] = 'blue2',
  ['vulcanist'] = 'red',
  ['warden'] = 'yellow',
  ['psychic'] = 'fg',
  ['miner'] = 'yellow2',
  ['merchant'] = 'yellow2',
  ['usurer'] = 'purple',
  ['gambler'] = 'yellow2',
  ['thief'] = 'red',
}


function build_localized_tables()
  character_names = {
    ['vagrant'] = T('char.vagrant.name'),
    ['swordsman'] = T('char.swordsman.name'),
    ['wizard'] = T('char.wizard.name'),
    ['magician'] = T('char.magician.name'),
    ['archer'] = T('char.archer.name'),
    ['scout'] = T('char.scout.name'),
    ['cleric'] = T('char.cleric.name'),
    ['outlaw'] = T('char.outlaw.name'),
    ['blade'] = T('char.blade.name'),
    ['elementor'] = T('char.elementor.name'),
    ['saboteur'] = T('char.saboteur.name'),
    ['bomber'] = T('char.bomber.name'),
    ['stormweaver'] = T('char.stormweaver.name'),
    ['sage'] = T('char.sage.name'),
    ['squire'] = T('char.squire.name'),
    ['cannoneer'] = T('char.cannoneer.name'),
    ['dual_gunner'] = T('char.dual_gunner.name'),
    ['hunter'] = T('char.hunter.name'),
    ['sentry'] = T('char.sentry.name'),
    ['chronomancer'] = T('char.chronomancer.name'),
    ['spellblade'] = T('char.spellblade.name'),
    ['psykeeper'] = T('char.psykeeper.name'),
    ['engineer'] = T('char.engineer.name'),
    ['plague_doctor'] = T('char.plague_doctor.name'),
    ['barbarian'] = T('char.barbarian.name'),
    ['juggernaut'] = T('char.juggernaut.name'),
    ['lich'] = T('char.lich.name'),
    ['cryomancer'] = T('char.cryomancer.name'),
    ['pyromancer'] = T('char.pyromancer.name'),
    ['corruptor'] = T('char.corruptor.name'),
    ['beastmaster'] = T('char.beastmaster.name'),
    ['launcher'] = T('char.launcher.name'),
    ['jester'] = T('char.jester.name'),
    ['assassin'] = T('char.assassin.name'),
    ['host'] = T('char.host.name'),
    ['carver'] = T('char.carver.name'),
    ['bane'] = T('char.bane.name'),
    ['psykino'] = T('char.psykino.name'),
    ['barrager'] = T('char.barrager.name'),
    ['highlander'] = T('char.highlander.name'),
    ['fairy'] = T('char.fairy.name'),
    ['priest'] = T('char.priest.name'),
    ['infestor'] = T('char.infestor.name'),
    ['flagellant'] = T('char.flagellant.name'),
    ['arcanist'] = T('char.arcanist.name'),
    ['illusionist'] = T('char.illusionist.name'),
    ['artificer'] = T('char.artificer.name'),
    ['witch'] = T('char.witch.name'),
    ['silencer'] = T('char.silencer.name'),
    ['vulcanist'] = T('char.vulcanist.name'),
    ['warden'] = T('char.warden.name'),
    ['psychic'] = T('char.psychic.name'),
    ['miner'] = T('char.miner.name'),
    ['merchant'] = T('char.merchant.name'),
    ['usurer'] = T('char.usurer.name'),
    ['gambler'] = T('char.gambler.name'),
    ['thief'] = T('char.thief.name'),
  }

  class_names = {
    ['ranger'] = T('class.ranger.name'),
    ['warrior'] = T('class.warrior.name'),
    ['mage'] = T('class.mage.name'),
    ['rogue'] = T('class.rogue.name'),
    ['healer'] = T('class.healer.name'),
    ['enchanter'] = T('class.enchanter.name'),
    ['nuker'] = T('class.nuker.name'),
    ['conjurer'] = T('class.conjurer.name'),
    ['psyker'] = T('class.psyker.name'),
    ['curser'] = T('class.curser.name'),
    ['forcer'] = T('class.forcer.name'),
    ['swarmer'] = T('class.swarmer.name'),
    ['voider'] = T('class.voider.name'),
    ['sorcerer'] = T('class.sorcerer.name'),
    ['mercenary'] = T('class.mercenary.name'),
    ['explorer'] = T('class.explorer.name'),
  }

  character_class_strings = {
    ['vagrant'] = T('char.vagrant.classes'),
    ['swordsman'] = T('char.swordsman.classes'),
    ['wizard'] = T('char.wizard.classes'),
    ['magician'] = T('char.magician.classes'),
    ['archer'] = T('char.archer.classes'),
    ['scout'] = T('char.scout.classes'),
    ['cleric'] = T('char.cleric.classes'),
    ['outlaw'] = T('char.outlaw.classes'),
    ['blade'] = T('char.blade.classes'),
    ['elementor'] = T('char.elementor.classes'),
    ['bomber'] = T('char.bomber.classes'),
    ['stormweaver'] = T('char.stormweaver.classes'),
    ['sage'] = T('char.sage.classes'),
    ['squire'] = T('char.squire.classes'),
    ['cannoneer'] = T('char.cannoneer.classes'),
    ['dual_gunner'] = T('char.dual_gunner.classes'),
    ['sentry'] = T('char.sentry.classes'),
    ['chronomancer'] = T('char.chronomancer.classes'),
    ['spellblade'] = T('char.spellblade.classes'),
    ['psykeeper'] = T('char.psykeeper.classes'),
    ['engineer'] = T('char.engineer.classes'),
    ['plague_doctor'] = T('char.plague_doctor.classes'),
    ['barbarian'] = T('char.barbarian.classes'),
    ['juggernaut'] = T('char.juggernaut.classes'),
    ['lich'] = T('char.lich.classes'),
    ['cryomancer'] = T('char.cryomancer.classes'),
    ['pyromancer'] = T('char.pyromancer.classes'),
    ['corruptor'] = T('char.corruptor.classes'),
    ['beastmaster'] = T('char.beastmaster.classes'),
    ['launcher'] = T('char.launcher.classes'),
    ['jester'] = T('char.jester.classes'),
    ['assassin'] = T('char.assassin.classes'),
    ['host'] = T('char.host.classes'),
    ['carver'] = T('char.carver.classes'),
    ['bane'] = T('char.bane.classes'),
    ['psykino'] = T('char.psykino.classes'),
    ['barrager'] = T('char.barrager.classes'),
    ['highlander'] = T('char.highlander.classes'),
    ['fairy'] = T('char.fairy.classes'),
    ['priest'] = T('char.priest.classes'),
    ['infestor'] = T('char.infestor.classes'),
    ['flagellant'] = T('char.flagellant.classes'),
    ['arcanist'] = T('char.arcanist.classes'),
    ['artificer'] = T('char.artificer.classes'),
    ['witch'] = T('char.witch.classes'),
    ['silencer'] = T('char.silencer.classes'),
    ['vulcanist'] = T('char.vulcanist.classes'),
    ['warden'] = T('char.warden.classes'),
    ['psychic'] = T('char.psychic.classes'),
    ['miner'] = T('char.miner.classes'),
    ['merchant'] = T('char.merchant.classes'),
    ['usurer'] = T('char.usurer.classes'),
    ['gambler'] = T('char.gambler.classes'),
    ['thief'] = T('char.thief.classes'),
  }

  character_descriptions = {
    ['vagrant'] = function(lvl) return T('char.vagrant.desc', get_character_stat('vagrant', lvl, 'dmg')) end,
    ['swordsman'] = function(lvl) return T('char.swordsman.desc', get_character_stat('swordsman', lvl, 'dmg'), math.round(get_character_stat('swordsman', lvl, 'dmg')*0.15, 2)) end,
    ['wizard'] = function(lvl) return T('char.wizard.desc', get_character_stat('wizard', lvl, 'dmg')) end,
    ['magician'] = function(lvl) return T('char.magician.desc', get_character_stat('magician', lvl, 'dmg')) end,
    ['archer'] = function(lvl) return T('char.archer.desc', get_character_stat('archer', lvl, 'dmg')) end,
    ['scout'] = function(lvl) return T('char.scout.desc', get_character_stat('scout', lvl, 'dmg')) end,
    ['cleric'] = function(lvl) return T('char.cleric.desc') end,
    ['outlaw'] = function(lvl) return T('char.outlaw.desc', get_character_stat('outlaw', lvl, 'dmg')) end,
    ['blade'] = function(lvl) return T('char.blade.desc', get_character_stat('blade', lvl, 'dmg')) end,
    ['elementor'] = function(lvl) return T('char.elementor.desc', get_character_stat('elementor', lvl, 'dmg')) end,
    ['saboteur'] = function(lvl) return T('char.saboteur.desc', get_character_stat('saboteur', lvl, 'dmg')) end,
    ['bomber'] = function(lvl) return T('char.bomber.desc', 2*get_character_stat('bomber', lvl, 'dmg')) end,
    ['stormweaver'] = function(lvl) return T('char.stormweaver.desc') end,
    ['sage'] = function(lvl) return T('char.sage.desc') end,
    ['squire'] = function(lvl) return T('char.squire.desc') end,
    ['cannoneer'] = function(lvl) return T('char.cannoneer.desc', 2*get_character_stat('cannoneer', lvl, 'dmg')) end,
    ['dual_gunner'] = function(lvl) return T('char.dual_gunner.desc', get_character_stat('dual_gunner', lvl, 'dmg')) end,
    ['hunter'] = function(lvl) return T('char.hunter.desc', get_character_stat('hunter', lvl, 'dmg')) end,
    ['sentry'] = function(lvl) return T('char.sentry.desc', get_character_stat('sentry', lvl, 'dmg')) end,
    ['chronomancer'] = function(lvl) return T('char.chronomancer.desc') end,
    ['spellblade'] = function(lvl) return T('char.spellblade.desc', get_character_stat('spellblade', lvl, 'dmg')) end,
    ['psykeeper'] = function(lvl) return T('char.psykeeper.desc') end,
    ['engineer'] = function(lvl) return T('char.engineer.desc', get_character_stat('engineer', lvl, 'dmg')) end,
    ['plague_doctor'] = function(lvl) return T('char.plague_doctor.desc', get_character_stat('plague_doctor', lvl, 'dmg')) end,
    ['barbarian'] = function(lvl) return T('char.barbarian.desc', get_character_stat('barbarian', lvl, 'dmg')) end,
    ['juggernaut'] = function(lvl) return T('char.juggernaut.desc', get_character_stat('juggernaut', lvl, 'dmg')) end,
    ['lich'] = function(lvl) return T('char.lich.desc', 2*get_character_stat('lich', lvl, 'dmg')) end,
    ['cryomancer'] = function(lvl) return T('char.cryomancer.desc', get_character_stat('cryomancer', lvl, 'dmg')) end,
    ['pyromancer'] = function(lvl) return T('char.pyromancer.desc', get_character_stat('pyromancer', lvl, 'dmg')) end,
    ['corruptor'] = function(lvl) return T('char.corruptor.desc', get_character_stat('corruptor', lvl, 'dmg')) end,
    ['beastmaster'] = function(lvl) return T('char.beastmaster.desc', get_character_stat('beastmaster', lvl, 'dmg')) end,
    ['launcher'] = function(lvl) return T('char.launcher.desc', 2*get_character_stat('launcher', lvl, 'dmg')) end,
    ['jester'] = function(lvl) return T('char.jester.desc') end,
    ['assassin'] = function(lvl) return T('char.assassin.desc', get_character_stat('assassin', lvl, 'dmg'), get_character_stat('assassin', lvl, 'dmg')/2) end,
    ['host'] = function(lvl) return T('char.host.desc') end,
    ['carver'] = function(lvl) return T('char.carver.desc') end,
    ['bane'] = function(lvl) return T('char.bane.desc') end,
    ['psykino'] = function(lvl) return T('char.psykino.desc') end,
    ['barrager'] = function(lvl) return T('char.barrager.desc', get_character_stat('barrager', lvl, 'dmg')) end,
    ['highlander'] = function(lvl) return T('char.highlander.desc', 5*get_character_stat('highlander', lvl, 'dmg')) end,
    ['fairy'] = function(lvl) return T('char.fairy.desc') end,
    ['priest'] = function(lvl) return T('char.priest.desc') end,
    ['infestor'] = function(lvl) return T('char.infestor.desc') end,
    ['flagellant'] = function(lvl) return T('char.flagellant.desc', 2*get_character_stat('flagellant', lvl, 'dmg')) end,
    ['arcanist'] = function(lvl) return T('char.arcanist.desc', get_character_stat('arcanist', lvl, 'dmg')) end,
    ['illusionist'] = function(lvl) return T('char.illusionist.desc', get_character_stat('illusionist', lvl, 'dmg')) end,
    ['artificer'] = function(lvl) return T('char.artificer.desc', get_character_stat('artificer', lvl, 'dmg')) end,
    ['witch'] = function(lvl) return T('char.witch.desc', get_character_stat('witch', lvl, 'dmg')) end,
    ['silencer'] = function(lvl) return T('char.silencer.desc') end,
    ['vulcanist'] = function(lvl) return T('char.vulcanist.desc', get_character_stat('vulcanist', lvl, 'dmg')) end,
    ['warden'] = function(lvl) return T('char.warden.desc') end,
    ['psychic'] = function(lvl) return T('char.psychic.desc', get_character_stat('psychic', lvl, 'dmg')) end,
    ['miner'] = function(lvl) return T('char.miner.desc', get_character_stat('miner', lvl, 'dmg')) end,
    ['merchant'] = function(lvl) return T('char.merchant.desc') end,
    ['usurer'] = function(lvl) return T('char.usurer.desc', get_character_stat('usurer', lvl, 'dmg')) end,
    ['gambler'] = function(lvl) return T('char.gambler.desc') end,
    ['thief'] = function(lvl) return T('char.thief.desc', 2*get_character_stat('thief', lvl, 'dmg')) end,
  }

  -- The title of a hero's level 3 effect, in colour once the effect is live and
  -- greyed out until then.
  character_effect_names = {}
  character_effect_names_gray = {}
  for character, color in pairs(effect_colors) do
    local name = T('char.' .. character .. '.effect_name')
    character_effect_names[character] = '[' .. color .. ']' .. name
    character_effect_names_gray[character] = '[light_bg]' .. name
  end

  character_effect_descriptions = {
    ['vagrant'] = function() return T('char.vagrant.effect_desc') end,
    ['swordsman'] = function() return T('char.swordsman.effect_desc') end,
    ['wizard'] = function() return T('char.wizard.effect_desc') end,
    ['magician'] = function() return T('char.magician.effect_desc') end,
    ['archer'] = function() return T('char.archer.effect_desc') end,
    ['scout'] = function() return T('char.scout.effect_desc') end,
    ['cleric'] = function() return T('char.cleric.effect_desc') end,
    ['outlaw'] = function() return T('char.outlaw.effect_desc') end,
    ['blade'] = function() return T('char.blade.effect_desc', math.round(get_character_stat('blade', 3, 'dmg')/3, 2)) end,
    ['elementor'] = function() return T('char.elementor.effect_desc') end,
    ['saboteur'] = function() return T('char.saboteur.effect_desc') end,
    ['bomber'] = function() return T('char.bomber.effect_desc') end,
    ['stormweaver'] = function() return T('char.stormweaver.effect_desc') end,
    ['sage'] = function() return T('char.sage.effect_desc', 3*get_character_stat('sage', 3, 'dmg')) end,
    ['squire'] = function() return T('char.squire.effect_desc') end,
    ['cannoneer'] = function() return T('char.cannoneer.effect_desc', get_character_stat('cannoneer', 3, 'dmg')/2) end,
    ['dual_gunner'] = function() return T('char.dual_gunner.effect_desc') end,
    ['hunter'] = function() return T('char.hunter.effect_desc') end,
    ['sentry'] = function() return T('char.sentry.effect_desc') end,
    ['chronomancer'] = function() return T('char.chronomancer.effect_desc') end,
    ['spellblade'] = function() return T('char.spellblade.effect_desc') end,
    ['psykeeper'] = function() return T('char.psykeeper.effect_desc') end,
    ['engineer'] = function() return T('char.engineer.effect_desc') end,
    ['plague_doctor'] = function() return T('char.plague_doctor.effect_desc', get_character_stat('plague_doctor', 3, 'dmg')) end,
    ['barbarian'] = function() return T('char.barbarian.effect_desc') end,
    ['juggernaut'] = function() return T('char.juggernaut.effect_desc', 4*get_character_stat('juggernaut', 3, 'dmg')) end,
    ['lich'] = function() return T('char.lich.effect_desc') end,
    ['cryomancer'] = function() return T('char.cryomancer.effect_desc') end,
    ['pyromancer'] = function() return T('char.pyromancer.effect_desc', get_character_stat('pyromancer', 3, 'dmg')) end,
    ['corruptor'] = function() return T('char.corruptor.effect_desc') end,
    ['beastmaster'] = function() return T('char.beastmaster.effect_desc') end,
    ['launcher'] = function() return T('char.launcher.effect_desc') end,
    ['jester'] = function() return T('char.jester.effect_desc') end,
    ['assassin'] = function() return T('char.assassin.effect_desc') end,
    ['host'] = function() return T('char.host.effect_desc') end,
    ['carver'] = function() return T('char.carver.effect_desc') end,
    ['bane'] = function() return T('char.bane.effect_desc') end,
    ['psykino'] = function() return T('char.psykino.effect_desc', 4*get_character_stat('psykino', 3, 'dmg')) end,
    ['barrager'] = function() return T('char.barrager.effect_desc') end,
    ['highlander'] = function() return T('char.highlander.effect_desc') end,
    ['fairy'] = function() return T('char.fairy.effect_desc') end,
    ['priest'] = function() return T('char.priest.effect_desc') end,
    ['infestor'] = function() return T('char.infestor.effect_desc') end,
    ['flagellant'] = function() return T('char.flagellant.effect_desc') end,
    ['arcanist'] = function() return T('char.arcanist.effect_desc') end,
    ['illusionist'] = function() return T('char.illusionist.effect_desc') end,
    ['artificer'] = function() return T('char.artificer.effect_desc') end,
    ['witch'] = function() return T('char.witch.effect_desc', get_character_stat('witch', 3, 'dmg')) end,
    ['silencer'] = function() return T('char.silencer.effect_desc', get_character_stat('silencer', 3, 'dmg')) end,
    ['vulcanist'] = function() return T('char.vulcanist.effect_desc') end,
    ['warden'] = function() return T('char.warden.effect_desc') end,
    ['psychic'] = function() return T('char.psychic.effect_desc') end,
    ['miner'] = function() return T('char.miner.effect_desc') end,
    ['merchant'] = function() return T('char.merchant.effect_desc') end,
    ['usurer'] = function() return T('char.usurer.effect_desc', 10*get_character_stat('usurer', 3, 'dmg')) end,
    ['gambler'] = function() return T('char.gambler.effect_desc') end,
    ['thief'] = function() return T('char.thief.effect_desc', 10*get_character_stat('thief', 3, 'dmg')) end,
  }

  -- The greyed-out copy of a description is the same sentence with the colour
  -- taken out, so it is derived rather than written down twice. Five of them
  -- used to be written down twice and had drifted: the greyed blade and wizard
  -- overstated their effect, which is a bad thing for a line that is only ever
  -- shown while a player is deciding whether to pay for it.
  character_effect_descriptions_gray = {}
  for character, describe_effect in pairs(character_effect_descriptions) do
    character_effect_descriptions_gray[character] = function()
      return '[light_bg]' .. (describe_effect():gsub('%[[^%]]*%]', ''))
    end
  end

  class_descriptions = {
    ['ranger'] = function(lvl) return T('class.ranger.desc', cls2(lvl, '3', '6'), cls2(lvl, '8%', '16%')) end,
    ['warrior'] = function(lvl) return T('class.warrior.desc', cls2(lvl, '3', '6'), cls2(lvl, '+25', '+50')) end,
    ['mage'] = function(lvl) return T('class.mage.desc', cls2(lvl, '3', '6'), cls2(lvl, '-15', '-30')) end,
    ['rogue'] = function(lvl) return T('class.rogue.desc', cls2(lvl, '3', '6'), cls2(lvl, '15%', '30%')) end,
    ['healer'] = function(lvl) return T('class.healer.desc', cls2(lvl, '2', '4'), cls2(lvl, '+15%', '+30%')) end,
    ['enchanter'] = function(lvl) return T('class.enchanter.desc', cls2(lvl, '2', '4'), cls2(lvl, '+15%', '+25%')) end,
    ['nuker'] = function(lvl) return T('class.nuker.desc', cls2(lvl, '3', '6'), cls2(lvl, '+15%', '+25%')) end,
    ['conjurer'] = function(lvl) return T('class.conjurer.desc', cls2(lvl, '2', '4'), cls2(lvl, '+25%', '+50%')) end,
    ['psyker'] = function(lvl) return T('class.psyker.desc', cls2(lvl, '2', '4'), cls2(lvl, '+2', '+4')) end,
    ['curser'] = function(lvl) return T('class.curser.desc', cls2(lvl, '2', '4'), cls2(lvl, '+1', '+3')) end,
    ['forcer'] = function(lvl) return T('class.forcer.desc', cls2(lvl, '2', '4'), cls2(lvl, '+25%', '+50%')) end,
    ['swarmer'] = function(lvl) return T('class.swarmer.desc', cls2(lvl, '2', '4'), cls2(lvl, '+1', '+3')) end,
    ['voider'] = function(lvl) return T('class.voider.desc', cls2(lvl, '2', '4'), cls2(lvl, '+20%', '+40%')) end,
    ['sorcerer'] = function(lvl) return T('class.sorcerer.desc', cls3(lvl, '2', '4', '6'), cls3(lvl, '4', '3', '2')) end,
    ['mercenary'] = function(lvl) return T('class.mercenary.desc', cls2(lvl, '2', '4'), cls2(lvl, '+8%', '+16%')) end,
    ['explorer'] = function(lvl) return T('class.explorer.desc') end,
  }

  passive_names = {
    ['centipede'] = T('passive.centipede.name'),
    ['ouroboros_technique_r'] = T('passive.ouroboros_technique_r.name'),
    ['ouroboros_technique_l'] = T('passive.ouroboros_technique_l.name'),
    ['amplify'] = T('passive.amplify.name'),
    ['resonance'] = T('passive.resonance.name'),
    ['ballista'] = T('passive.ballista.name'),
    ['call_of_the_void'] = T('passive.call_of_the_void.name'),
    ['crucio'] = T('passive.crucio.name'),
    ['speed_3'] = T('passive.speed_3.name'),
    ['damage_4'] = T('passive.damage_4.name'),
    ['shoot_5'] = T('passive.shoot_5.name'),
    ['death_6'] = T('passive.death_6.name'),
    ['lasting_7'] = T('passive.lasting_7.name'),
    ['defensive_stance'] = T('passive.defensive_stance.name'),
    ['offensive_stance'] = T('passive.offensive_stance.name'),
    ['kinetic_bomb'] = T('passive.kinetic_bomb.name'),
    ['porcupine_technique'] = T('passive.porcupine_technique.name'),
    ['last_stand'] = T('passive.last_stand.name'),
    ['seeping'] = T('passive.seeping.name'),
    ['deceleration'] = T('passive.deceleration.name'),
    ['annihilation'] = T('passive.annihilation.name'),
    ['malediction'] = T('passive.malediction.name'),
    ['hextouch'] = T('passive.hextouch.name'),
    ['whispers_of_doom'] = T('passive.whispers_of_doom.name'),
    ['tremor'] = T('passive.tremor.name'),
    ['heavy_impact'] = T('passive.heavy_impact.name'),
    ['fracture'] = T('passive.fracture.name'),
    ['meat_shield'] = T('passive.meat_shield.name'),
    ['hive'] = T('passive.hive.name'),
    ['baneling_burst'] = T('passive.baneling_burst.name'),
    ['blunt_arrow'] = T('passive.blunt_arrow.name'),
    ['explosive_arrow'] = T('passive.explosive_arrow.name'),
    ['divine_machine_arrow'] = T('passive.divine_machine_arrow.name'),
    ['chronomancy'] = T('passive.chronomancy.name'),
    ['awakening'] = T('passive.awakening.name'),
    ['divine_punishment'] = T('passive.divine_punishment.name'),
    ['assassination'] = T('passive.assassination.name'),
    ['flying_daggers'] = T('passive.flying_daggers.name'),
    ['ultimatum'] = T('passive.ultimatum.name'),
    ['magnify'] = T('passive.magnify.name'),
    ['echo_barrage'] = T('passive.echo_barrage.name'),
    ['unleash'] = T('passive.unleash.name'),
    ['reinforce'] = T('passive.reinforce.name'),
    ['payback'] = T('passive.payback.name'),
    ['enchanted'] = T('passive.enchanted.name'),
    ['freezing_field'] = T('passive.freezing_field.name'),
    ['burning_field'] = T('passive.burning_field.name'),
    ['gravity_field'] = T('passive.gravity_field.name'),
    ['magnetism'] = T('passive.magnetism.name'),
    ['insurance'] = T('passive.insurance.name'),
    ['dividends'] = T('passive.dividends.name'),
    ['berserking'] = T('passive.berserking.name'),
    ['unwavering_stance'] = T('passive.unwavering_stance.name'),
    ['unrelenting_stance'] = T('passive.unrelenting_stance.name'),
    ['blessing'] = T('passive.blessing.name'),
    ['haste'] = T('passive.haste.name'),
    ['divine_barrage'] = T('passive.divine_barrage.name'),
    ['orbitism'] = T('passive.orbitism.name'),
    ['psyker_orbs'] = T('passive.psyker_orbs.name'),
    ['psychosense'] = T('passive.psychosense.name'),
    ['psychosink'] = T('passive.psychosink.name'),
    ['rearm'] = T('passive.rearm.name'),
    ['taunt'] = T('passive.taunt.name'),
    ['construct_instability'] = T('passive.construct_instability.name'),
    ['intimidation'] = T('passive.intimidation.name'),
    ['vulnerability'] = T('passive.vulnerability.name'),
    ['temporal_chains'] = T('passive.temporal_chains.name'),
    ['ceremonial_dagger'] = T('passive.ceremonial_dagger.name'),
    ['homing_barrage'] = T('passive.homing_barrage.name'),
    ['critical_strike'] = T('passive.critical_strike.name'),
    ['noxious_strike'] = T('passive.noxious_strike.name'),
    ['infesting_strike'] = T('passive.infesting_strike.name'),
    ['kinetic_strike'] = T('passive.kinetic_strike.name'),
    ['burning_strike'] = T('passive.burning_strike.name'),
    ['lucky_strike'] = T('passive.lucky_strike.name'),
    ['healing_strike'] = T('passive.healing_strike.name'),
    ['stunning_strike'] = T('passive.stunning_strike.name'),
    ['silencing_strike'] = T('passive.silencing_strike.name'),
    ['warping_shots'] = T('passive.warping_shots.name'),
    ['culling_strike'] = T('passive.culling_strike.name'),
    ['lightning_strike'] = T('passive.lightning_strike.name'),
    ['psycholeak'] = T('passive.psycholeak.name'),
    ['divine_blessing'] = T('passive.divine_blessing.name'),
    ['hardening'] = T('passive.hardening.name'),
  }

  passive_descriptions = {
    ['centipede'] = T('passive.centipede.desc'),
    ['ouroboros_technique_r'] = T('passive.ouroboros_technique_r.desc'),
    ['ouroboros_technique_l'] = T('passive.ouroboros_technique_l.desc'),
    ['amplify'] = T('passive.amplify.desc'),
    ['resonance'] = T('passive.resonance.desc'),
    ['ballista'] = T('passive.ballista.desc'),
    ['call_of_the_void'] = T('passive.call_of_the_void.desc'),
    ['crucio'] = T('passive.crucio.desc'),
    ['speed_3'] = T('passive.speed_3.desc'),
    ['damage_4'] = T('passive.damage_4.desc'),
    ['shoot_5'] = T('passive.shoot_5.desc'),
    ['death_6'] = T('passive.death_6.desc'),
    ['lasting_7'] = T('passive.lasting_7.desc'),
    ['defensive_stance'] = T('passive.defensive_stance.desc'),
    ['offensive_stance'] = T('passive.offensive_stance.desc'),
    ['kinetic_bomb'] = T('passive.kinetic_bomb.desc'),
    ['porcupine_technique'] = T('passive.porcupine_technique.desc'),
    ['last_stand'] = T('passive.last_stand.desc'),
    ['seeping'] = T('passive.seeping.desc'),
    ['deceleration'] = T('passive.deceleration.desc'),
    ['annihilation'] = T('passive.annihilation.desc'),
    ['malediction'] = T('passive.malediction.desc'),
    ['hextouch'] = T('passive.hextouch.desc'),
    ['whispers_of_doom'] = T('passive.whispers_of_doom.desc'),
    ['tremor'] = T('passive.tremor.desc'),
    ['heavy_impact'] = T('passive.heavy_impact.desc'),
    ['fracture'] = T('passive.fracture.desc'),
    ['meat_shield'] = T('passive.meat_shield.desc'),
    ['hive'] = T('passive.hive.desc'),
    ['baneling_burst'] = T('passive.baneling_burst.desc'),
    ['blunt_arrow'] = T('passive.blunt_arrow.desc'),
    ['explosive_arrow'] = T('passive.explosive_arrow.desc'),
    ['divine_machine_arrow'] = T('passive.divine_machine_arrow.desc'),
    ['chronomancy'] = T('passive.chronomancy.desc'),
    ['awakening'] = T('passive.awakening.desc'),
    ['divine_punishment'] = T('passive.divine_punishment.desc'),
    ['assassination'] = T('passive.assassination.desc'),
    ['flying_daggers'] = T('passive.flying_daggers.desc'),
    ['ultimatum'] = T('passive.ultimatum.desc'),
    ['magnify'] = T('passive.magnify.desc'),
    ['echo_barrage'] = T('passive.echo_barrage.desc'),
    ['unleash'] = T('passive.unleash.desc'),
    ['reinforce'] = T('passive.reinforce.desc'),
    ['payback'] = T('passive.payback.desc'),
    ['enchanted'] = T('passive.enchanted.desc'),
    ['freezing_field'] = T('passive.freezing_field.desc'),
    ['burning_field'] = T('passive.burning_field.desc'),
    ['gravity_field'] = T('passive.gravity_field.desc'),
    ['magnetism'] = T('passive.magnetism.desc'),
    ['insurance'] = T('passive.insurance.desc'),
    ['dividends'] = T('passive.dividends.desc'),
    ['berserking'] = T('passive.berserking.desc'),
    ['unwavering_stance'] = T('passive.unwavering_stance.desc'),
    ['unrelenting_stance'] = T('passive.unrelenting_stance.desc'),
    ['blessing'] = T('passive.blessing.desc'),
    ['haste'] = T('passive.haste.desc'),
    ['divine_barrage'] = T('passive.divine_barrage.desc'),
    ['orbitism'] = T('passive.orbitism.desc'),
    ['psyker_orbs'] = T('passive.psyker_orbs.desc'),
    ['psychosense'] = T('passive.psychosense.desc'),
    ['psychosink'] = T('passive.psychosink.desc'),
    ['rearm'] = T('passive.rearm.desc'),
    ['taunt'] = T('passive.taunt.desc'),
    ['construct_instability'] = T('passive.construct_instability.desc'),
    ['intimidation'] = T('passive.intimidation.desc'),
    ['vulnerability'] = T('passive.vulnerability.desc'),
    ['temporal_chains'] = T('passive.temporal_chains.desc'),
    ['ceremonial_dagger'] = T('passive.ceremonial_dagger.desc'),
    ['homing_barrage'] = T('passive.homing_barrage.desc'),
    ['critical_strike'] = T('passive.critical_strike.desc'),
    ['noxious_strike'] = T('passive.noxious_strike.desc'),
    ['infesting_strike'] = T('passive.infesting_strike.desc'),
    ['kinetic_strike'] = T('passive.kinetic_strike.desc'),
    ['burning_strike'] = T('passive.burning_strike.desc'),
    ['lucky_strike'] = T('passive.lucky_strike.desc'),
    ['healing_strike'] = T('passive.healing_strike.desc'),
    ['stunning_strike'] = T('passive.stunning_strike.desc'),
    ['silencing_strike'] = T('passive.silencing_strike.desc'),
    ['warping_shots'] = T('passive.warping_shots.desc'),
    ['culling_strike'] = T('passive.culling_strike.desc'),
    ['lightning_strike'] = T('passive.lightning_strike.desc'),
    ['psycholeak'] = T('passive.psycholeak.desc'),
    ['divine_blessing'] = T('passive.divine_blessing.desc'),
    ['hardening'] = T('passive.hardening.desc'),
  }

  passive_descriptions_level = {
    ['centipede'] = function(lvl) return T('passive.centipede.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['ouroboros_technique_r'] = function(lvl) return T('passive.ouroboros_technique_r.desc_level', ts(lvl, '2', '3', '4')) end,
    ['ouroboros_technique_l'] = function(lvl) return T('passive.ouroboros_technique_l.desc_level', ts(lvl, '+15%', '25%', '35%')) end,
    ['amplify'] = function(lvl) return T('passive.amplify.desc_level', ts(lvl, '+20%', '35%', '50%')) end,
    ['resonance'] = function(lvl) return T('passive.resonance.desc_level', ts(lvl, '+3%', '5%', '7%')) end,
    ['ballista'] = function(lvl) return T('passive.ballista.desc_level', ts(lvl, '+20%', '35%', '50%')) end,
    ['call_of_the_void'] = function(lvl) return T('passive.call_of_the_void.desc_level', ts(lvl, '+30%', '60%', '90%')) end,
    ['crucio'] = function(lvl) return T('passive.crucio.desc_level', ts(lvl, '20%', '30%', '40%')) end,
    ['speed_3'] = function(lvl) return T('passive.speed_3.desc_level') end,
    ['damage_4'] = function(lvl) return T('passive.damage_4.desc_level') end,
    ['shoot_5'] = function(lvl) return T('passive.shoot_5.desc_level') end,
    ['death_6'] = function(lvl) return T('passive.death_6.desc_level') end,
    ['lasting_7'] = function(lvl) return T('passive.lasting_7.desc_level') end,
    ['defensive_stance'] = function(lvl) return T('passive.defensive_stance.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['offensive_stance'] = function(lvl) return T('passive.offensive_stance.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['kinetic_bomb'] = function(lvl) return T('passive.kinetic_bomb.desc_level') end,
    ['porcupine_technique'] = function(lvl) return T('passive.porcupine_technique.desc_level') end,
    ['last_stand'] = function(lvl) return T('passive.last_stand.desc_level') end,
    ['seeping'] = function(lvl) return T('passive.seeping.desc_level', ts(lvl, '-15%', '25%', '35%')) end,
    ['deceleration'] = function(lvl) return T('passive.deceleration.desc_level', ts(lvl, '-15%', '25%', '35%')) end,
    ['annihilation'] = function(lvl) return T('passive.annihilation.desc_level') end,
    ['malediction'] = function(lvl) return T('passive.malediction.desc_level', ts(lvl, '+1', '3', '5')) end,
    ['hextouch'] = function(lvl) return T('passive.hextouch.desc_level', ts(lvl, '10', '15', '20')) end,
    ['whispers_of_doom'] = function(lvl) return T('passive.whispers_of_doom.desc_level', ts(lvl, '100', '150', '200'), ts(lvl, '4', '3', '2')) end,
    ['tremor'] = function(lvl) return T('passive.tremor.desc_level') end,
    ['heavy_impact'] = function(lvl) return T('passive.heavy_impact.desc_level') end,
    ['fracture'] = function(lvl) return T('passive.fracture.desc_level') end,
    ['meat_shield'] = function(lvl) return T('passive.meat_shield.desc_level') end,
    ['hive'] = function(lvl) return T('passive.hive.desc_level', ts(lvl, '+1', '2', '3')) end,
    ['baneling_burst'] = function(lvl) return T('passive.baneling_burst.desc_level', ts(lvl, '50', '100', '150')) end,
    ['blunt_arrow'] = function(lvl) return T('passive.blunt_arrow.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['explosive_arrow'] = function(lvl) return T('passive.explosive_arrow.desc_level', ts(lvl, '+10%', '20%', '30%'), ts(lvl, '10%', '20%', '30%')) end,
    ['divine_machine_arrow'] = function(lvl) return T('passive.divine_machine_arrow.desc_level', ts(lvl, '10%', '20%', '30%'), ts(lvl, '1', '2', '3')) end,
    ['chronomancy'] = function(lvl) return T('passive.chronomancy.desc_level', ts(lvl, '15%', '25%', '35%')) end,
    ['awakening'] = function(lvl) return T('passive.awakening.desc_level', ts(lvl, '+50%', '75%', '100%')) end,
    ['divine_punishment'] = function(lvl) return T('passive.divine_punishment.desc_level') end,
    ['assassination'] = function(lvl) return T('passive.assassination.desc_level', ts(lvl, '8x', '10x', '12x')) end,
    ['flying_daggers'] = function(lvl) return T('passive.flying_daggers.desc_level', ts(lvl, '+2', '3', '4')) end,
    ['ultimatum'] = function(lvl) return T('passive.ultimatum.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['magnify'] = function(lvl) return T('passive.magnify.desc_level', ts(lvl, '+20%', '35%', '50%')) end,
    ['echo_barrage'] = function(lvl) return T('passive.echo_barrage.desc_level', ts(lvl, '10%', '20%', '30%'), ts(lvl, '1', '2', '3')) end,
    ['unleash'] = function(lvl) return T('passive.unleash.desc_level') end,
    ['reinforce'] = function(lvl) return T('passive.reinforce.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['payback'] = function(lvl) return T('passive.payback.desc_level', ts(lvl, '+2%', '5%', '8%')) end,
    ['enchanted'] = function(lvl) return T('passive.enchanted.desc_level', ts(lvl, '+33%', '66%', '99%')) end,
    ['freezing_field'] = function(lvl) return T('passive.freezing_field.desc_level') end,
    ['burning_field'] = function(lvl) return T('passive.burning_field.desc_level') end,
    ['gravity_field'] = function(lvl) return T('passive.gravity_field.desc_level') end,
    ['magnetism'] = function(lvl) return T('passive.magnetism.desc_level') end,
    ['insurance'] = function(lvl) return T('passive.insurance.desc_level') end,
    ['dividends'] = function(lvl) return T('passive.dividends.desc_level') end,
    ['berserking'] = function(lvl) return T('passive.berserking.desc_level', ts(lvl, '+50%', '75%', '100%')) end,
    ['unwavering_stance'] = function(lvl) return T('passive.unwavering_stance.desc_level', ts(lvl, '+4%', '8%', '12%')) end,
    ['unrelenting_stance'] = function(lvl) return T('passive.unrelenting_stance.desc_level', ts(lvl, '+2%', '5%', '8%')) end,
    ['blessing'] = function(lvl) return T('passive.blessing.desc_level', ts(lvl, '+10%', '20%', '30%')) end,
    ['haste'] = function(lvl) return T('passive.haste.desc_level') end,
    ['divine_barrage'] = function(lvl) return T('passive.divine_barrage.desc_level', ts(lvl, '20%', '40%', '60%')) end,
    ['orbitism'] = function(lvl) return T('passive.orbitism.desc_level', ts(lvl, '+25%', '50%', '75%')) end,
    ['psyker_orbs'] = function(lvl) return T('passive.psyker_orbs.desc_level', ts(lvl, '+1', '2', '4')) end,
    ['psychosense'] = function(lvl) return T('passive.psychosense.desc_level', ts(lvl, '+33%', '66%', '99%')) end,
    ['psychosink'] = function(lvl) return T('passive.psychosink.desc_level', ts(lvl, '+40%', '80%', '120%')) end,
    ['rearm'] = function(lvl) return T('passive.rearm.desc_level') end,
    ['taunt'] = function(lvl) return T('passive.taunt.desc_level', ts(lvl, '10%', '20%', '30%')) end,
    ['construct_instability'] = function(lvl) return T('passive.construct_instability.desc_level', ts(lvl, '100', '150', '200%')) end,
    ['intimidation'] = function(lvl) return T('passive.intimidation.desc_level', ts(lvl, '-10', '20', '30%')) end,
    ['vulnerability'] = function(lvl) return T('passive.vulnerability.desc_level', ts(lvl, '+10', '20', '30%')) end,
    ['temporal_chains'] = function(lvl) return T('passive.temporal_chains.desc_level', ts(lvl, '10', '20', '30%')) end,
    ['ceremonial_dagger'] = function(lvl) return T('passive.ceremonial_dagger.desc_level') end,
    ['homing_barrage'] = function(lvl) return T('passive.homing_barrage.desc_level', ts(lvl, '8', '16', '24%')) end,
    ['critical_strike'] = function(lvl) return T('passive.critical_strike.desc_level', ts(lvl, '5', '10', '15%')) end,
    ['noxious_strike'] = function(lvl) return T('passive.noxious_strike.desc_level', ts(lvl, '8', '16', '24%')) end,
    ['infesting_strike'] = function(lvl) return T('passive.infesting_strike.desc_level', ts(lvl, '10', '20', '30%')) end,
    ['kinetic_strike'] = function(lvl) return T('passive.kinetic_strike.desc_level', ts(lvl, '10', '20', '30%')) end,
    ['burning_strike'] = function(lvl) return T('passive.burning_strike.desc_level') end,
    ['lucky_strike'] = function(lvl) return T('passive.lucky_strike.desc_level') end,
    ['healing_strike'] = function(lvl) return T('passive.healing_strike.desc_level') end,
    ['stunning_strike'] = function(lvl) return T('passive.stunning_strike.desc_level', ts(lvl, '8', '16', '24%')) end,
    ['silencing_strike'] = function(lvl) return T('passive.silencing_strike.desc_level', ts(lvl, '8', '16', '24%')) end,
    ['warping_shots'] = function(lvl) return T('passive.warping_shots.desc_level', ts(lvl, '1', '2', '3')) end,
    ['culling_strike'] = function(lvl) return T('passive.culling_strike.desc_level', ts(lvl, '10', '20', '30%')) end,
    ['lightning_strike'] = function(lvl) return T('passive.lightning_strike.desc_level', ts(lvl, '5', '10', '15%'), ts(lvl, '60', '80', '100%')) end,
    ['psycholeak'] = function(lvl) return T('passive.psycholeak.desc_level') end,
    ['divine_blessing'] = function(lvl) return T('passive.divine_blessing.desc_level') end,
    ['hardening'] = function(lvl) return T('passive.hardening.desc_level') end,
  }
end
